### ISSUE TITLE
OLD-6182: POS Paypal payment process not working - wrong link used

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#45] opened 2012-10-14 00:32 UTC
## Description

when you insert an order with pos procedure, if you select Paypal as payment method, the procedure ask you to complete the paypal payment, but it is wrong.
When paypal is selected, the system has to send a payment request to customer
###### Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.2 - POS Finalization
###### #19 Updated by Chris DioscouriChris Paschen. 8 months ago

OK ... that will help a LOT to get 0.8.3 out the door faster.

It will also give us time to focus on POS more in 0.8.4.

I'm going to do some more detailed testing on POS (esp. UI issues).
Anyone else 'lurking', please join me in testing the POS system.
Let's add Bug reports and FRs so that we can get everything written down and tackle the main issues.
(We aren't going to create the best POS in 0.8.4, but please do add your 'dreams' as FRs now - so that they don't get missed/forgotten as we move ahead).
###### #18 Updated by Lukas Polak 8 months ago

Status changed from In Progress to New
Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.9 - Misc Bug Fixes and New Features

I agree Chris. We can try to fix POS related issues in 0.8.4 -> that should take some pressure off our shoulders when working on 0.8.3.

Lukas
###### #17 Updated by Chris DioscouriChris Paschen. 8 months ago

Lukas ... I'm thinking we should move this (along with all other POS issues) to 0.8.4 so that POS would be the main focus for 0.8.4 - other than plugins.
The entire POS process really isn't intuitive (OR has some significant workflow problems).
If you agree, please go ahead and move this to 0.8.4.
###### #16 Updated by Chris DioscouriChris Paschen. 9 months ago

Subject changed from send Paypal invoice during POS to POS Paypal payment process not working - wrong link used
###### #15 Updated by Alessandro Manfré 9 months ago

Don't worry Chris ;)
###### #14 Updated by Chris DioscouriChris Paschen. 9 months ago

Priority changed from Normal to High

Sorry - I've been testing and getting error screens.

It appears that it's taking you to the main PayPal login page - not a payment page.

HOWEVER ... I'm seeing 2 different bugs in this process right now (0.8.3 E).
1. In FF - the popup box appears, but when you click the paypal button, no window opens
2. In Chrome - the popup box never appears
3. In IE9 - the popup box appears with this warning:
   "This content cannot be displayed in a frame / To help protect the security of the information you enter into this website, the publisher of this content does not allow it to be displayed in a frame. / What you can try: Open this content in a new window" 
   When you click on this link (to open in a new window), you get the main PayPal login page (not a payment page).

So it looks like we've got a wrong URL posting here.

(Alessandro - sorry this took so long).

So we've got two problems here.
###### #13 Updated by Alessandro Manfré 9 months ago

sorry Chris, I think there is an missunderstanding. I don't need additionl feature about this topic.

For example, when you take an order by phone, and your custumer asks to pay with paypal, then you insert a POS order and select Paypal as payment method. At this point an popup windows is showed and here you see the paypal button. If you click on this button, you go to paypal website and paypal asks Username and Password (or credit card details), but You can't ask to your customer username e password of his paypal accout.

It is a paypal pluging bug, when you place a pos order, plugin has to send to paypal the right information to send request payment to user
###### #12 Updated by Chris DioscouriChris Paschen. 9 months ago

That would need to be a FR (to 'request payment').

The original intention of the POS was to take orders by phone - esp. for users who aren't using online services (esp. older users). So for this 'bug', we just need to be able to take the card info and process right in the admin side. (Which I believe it should if the link was working properly.)

If you want the other function, I'd suggest creating a new FR to have a button to click to 'request payment from user'.
###### #11 Updated by Alessandro Manfré 9 months ago

if you click on the paypal button so paypal ask you username e password, then it's no possbile complete payment for admin who has inserted the order.

from my point of view, the best way is send a payment requet by paypal when admin click on paypal button at the end of POS
###### #10 Updated by Chris DioscouriChris Paschen. 9 months ago

Status changed from Unconfirmed to In Progress
Assignee set to Lukas Polak
Affected Version changed from 0.8.0 to 0.8.0 / 0.8.3 pre-release d

Sorry for the delay in this one.

In going back to the original note on this:

When paypal is selected, the system has to send a payment request to customer

This is NOT the functionality that was designed into the POS system.

It should open a window that allows you to click on the Paypal button - which it does.

However, when you click on the paypal button, it should open the paypal screen so that you can enter the buyer's CC info.

It DOES NOT do that presently.

When you click on the paypal button it doesn't open the paypal window (although the link looks like it is proper).

So the only present 'bug' is that it doesn't open the window to paypal when you click the paypal button.
###### #9 Updated by Chris DioscouriChris Paschen. 12 months ago

Target version changed from Version 0.8.2 - New Features and Bug Fixes to Version 0.9.0 - Major Core Fixes
###### #8 Updated by Chris DioscouriChris Paschen. about 1 year ago

Target version changed from Version 0.8.1 - Bug Fixes to Version 0.8.2 - New Features and Bug Fixes
###### #7 Updated by Chris DioscouriChris Paschen. about 1 year ago

Zoltan,

Alessandro is using STD paypal (not pro) so it 'shouldn't' be against the terms to turn it off.

In addition, I didn't mean permanently, but just to turn it off temporarily to test - to see if the express is causing the problem.

NOTE: Paypal Pro plugin is causing random users problems right now. It's already listed for review.
###### #6 Updated by Chris DioscouriChris Paschen. about 1 year ago

Alessandro,

That is strange - you shouldn't have to click on any link.

I'll give it a look and see what I can see.
###### #5 Updated by Alessandro Manfré about 1 year ago

Sorry I'm not sure we are align

My issue is in back-end, when an admin inserts an order manually and sets as payment method paypal.

form "is wrong" means that It is impossible for an admin to insert an order and pay the same order itself.
admin inserts the order so the order has paid from the customer clicking on a paypal link sent by tienda system
###### #4 Updated by Zoltan Janosi about 1 year ago

Chris,

FYI - the last time I checked the PayPal pro terms of use, it seemed that you were required to have the PayPal Express checkout featured along with the credit card option, on your checkout page. Unless I mis-read something, this would be something to think with in the optimization of the payment plugins. (I.e. it's not something "nice to have" to have the Express checkout work correctly in PayPal Pro, but a contractual requirement for those using PayPal Pro.)
###### #3 Updated by Chris DioscouriChris Paschen. about 1 year ago

Paypal is now offering 'express payment' features. You can disable those through paypal (last I checked). Having the express payment features enabled is known to be causing problems with the paypal pro plugin.
###### #2 Updated by Alessandro Manfré about 1 year ago

paypal std
what do you mean "express payments enabled"?
###### #1 Updated by Chris DioscouriChris Paschen. about 1 year ago

Category set to Admin - Order Management
Status changed from New to Unconfirmed
Target version set to Version 0.8.1 - Bug Fixes

Alessandro,

What do you mean that 'it is wrong'?

Is this using paypal std or pro (and are you testing with the express payments enabled?)

**Comment by ChrisFrench** [comment] 2012-11-05 05:19
https://www.x.com/devzone/articles/how-use-paypal-invoicing-apis-php

This will probably help

**Comment by ChrisFrench** [comment] 2012-11-05 16:54
So for anyone coming into the ticket later,  the problem is that the paypal system works, and can checkout just fine. 

However the problem is that the most likely case for this feature is that someone  is taking an order over the phone, or manually inputing and emailed order and doesn't have access to the persons paypal information. 

so what I suggest is instead of  taking away the option to pay right now with paypal, maybe we make a new plugin, or option that instead of loading paypal it sends a payment request. 

Maybe this could be an invoice payment method ?

**Comment by rdiaztushman** [comment] 2012-11-05 17:06
I like the idea of a "bill me late" type of payment plugin.  It would essentially work like the offline-payments plugin, leaving the order in pre-payment status, but would trigger an invoice to be sent via paypal.

Add another ticket for that as a feature request, link it to this one, and then close this ticket.

**Comment by ChrisFrench** [comment] 2012-11-19 01:52
Ok since we are just making a new payment option I am closing this because it is no  longer a bug but a feature!

https://github.com/dioscouri/tienda/issues/129

**Closed as completed by ChrisFrench** 2012-11-19 01:52 UTC
Labels: enhancement
